
FIRST: 
	@echo "Use the following Makefiles for compiling:" 
	@echo 
	@echo "make <targets>                    - create cygwin targets" 
	@echo "make -f Makefile.cygwin <targets> - create cygwin targets" 
	@echo "make -f Makefile.mingw  <targets> - create mingw targets"
	@echo 
	@echo "avaliable targets:" 
	@echo
	@echo "all imagehelper rebase rebind unbind clean doc indent ... " 

include Makefile.in


